# Copyright (c) 2018 Rishiyur S. Nikhil.  All Rights Reserved.

# See LICENSE in this repo for license details.

# Runs a Python script
#    which runs the Forvis executable on all ELF tests in ../TestPrograms/
#    placing the output log for each test into Logs/
#    (see Python code for tests ignored because features are not yet implemented)

.PHONY: default
default:
	./Run_all_tests.py  ../TestPrograms  Logs
